name: "Build Pull Request"

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.**'
      - 'LICENSE'
      - 'ACKNOWLEDGEMENTS'
      - '**.md'

jobs:
  build:
    name: "Build PR"
    if: ${{ (github.event.action == 'synchronize' && github.event.label.name != 'skip preview') || github.event.action != 'synchronize' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: actions/setup-node@v4.0.2
      with:
        node-version: current
        cache: 'npm'
    - run: npm ci
    - name: Run test
      uses: cloudflare/wrangler-action@v3.4.1
      with:
        apiToken: 'dummy-key-that-should-make-the-action-run-lol'
        command: deploy --env pr --dry-run --outdir ./out
